### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mcwinter07**

### CODE REVIEW

**Comment by arunoda** [comment]
Hey @mcwinter07, I'm from ZEIT and I can see you are having some issues.
You can't deploy your app because via PRs because we only support using env variable via the following format:

```
{
  "env": {
    "JWT_SECRET": "@jwt-secret",
    "SERVER_PORT": 3000
  }
}
```

**Comment by mcwinter07** [comment]
Hi there! Thanks. We're having a bit of a play with it, now. We had attempted to deploy in this fashion before, with exactly the format you suggested above, but we had an error report from the bot stating that "env must be an array" ?

**Comment by arunoda** [comment]
Oh really. That's weird.
Let me check.

**Comment by arunoda** [comment]
I can see it: https://github.com/mcwinter07/little-bow-peep/pull/1
It shouldn't be like that.

Let me try to fix it.

**Comment by mcwinter07** [comment]
Hey, thanks @arunoda. Appreciate it :)

**Comment by arunoda** [comment]
Got it.
I think I found the issue.
Basically, it's a messaging issue.
(Will fix that)

set the `PORT` env to `"3000"` not `3000`.
Value for the env var should be a string.

That will fix your issue.

**Comment by oheydrew** [comment]
Thanks @arunoda, we'll give that a shot, now. Just going to check the change works locally

**Comment by arunoda** [comment]
@oheydrew awesome.

**Pull request merged**
