### PR TITLE
Update server port now.json

### PR DESCRIPTION
**Pull request by mcwinter07**
stringified port for now.json

### CODE REVIEW

**Comment by arunoda** [comment]
@mcwinter07 here's the issue:

screen shot 2018-06-28 at 12 36 31 pm

**Comment by arunoda** [comment]
Try scaling down to 0 some of the instances.

**Comment by arunoda** [comment]
Anyway, we'll have better have better error handling very very soon.

**Comment by oheydrew** [comment]
Thanks, @arunoda. We're pretty new to now, previously just used Heroku. I appreciate the help - Indeed, it'd be great to be able to see full error logs like you've provided! :)

Any tips on where we might scale down the instances?

**Comment by arunoda** [comment]
@oheydrew This is how can scale deployments: https://zeit.co/docs/getting-started/scaling#fixed-scaling

Basically all the deployments are in min: 0 max: 0 state.

Since you need to scale down old deployments, you need to run 

> now <deployment url> 0

You can go the deployments tab and see those deployments: https://zeit.co/dashboard/deployments

**Comment by oheydrew** [comment]
Thanks, @arunoda - We got the test going, thanks to your help. It's an interesting system, we'll have to play with it more and get used to it! :)

**Pull request merged**
